# Generated by Django 4.0.1 on 2022-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_runner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('book', models.CharField(choices=[('C', 'Chemistry'), ('G', 'Geography'), ('M', 'Mathematics'), ('E', 'English')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='runner',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
